### ISSUE TITLE
Advice needed :-) on implementation of Codecov without key on Travis

### ISSUE THREAD

**Issue by Cleop** [dwyl/learn-istanbul#12]
I'm trying to use Codecov on Travis without using the key as you told me it can be done without and so in the name of efficiency I want to learn how it's done!
My .travis.yml and package.json look like yours:
https://github.com/Cleop/triumph-website/blob/master/.travis.yml#L3-L6
https://github.com/Cleop/triumph-website/blob/master/package.json#L10

And I'm registered on Codecov and have selected the repo.

However I'm not getting any data on Codecov when I merge PR or on the badge on my README.

Any advice would be greatly appreciated 😄  Thank you!

**Comment by Cleop** [comment]
The last few amends I've made using Travis to try and fix this have all failed on the build. The only one which passed in Travis but didn't have working Codecov looked like this in the package.json:

before_install:
  - pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run coverage

which is what I had used in a previous project which had used the token.

**Comment by nelsonic** [comment]
Hi @Cleop _thank you_ for creating this question! ❤️ 
Are the [instructions in the readme for setting up Codecov](https://github.com/dwyl/learn-istanbul/tree/1a01703501e8d641f4650793425b49e2b804a233#tracking-coverage-as-a-service) no longer valid? 😞 
I'm _just_ about to set this up for my _weekend_ project: https://github.com/dwyl/stars so will be _checking_ if I can replicate it. will report back shortly. thanks! 👍

**Comment by nelsonic** [comment]
Hi @Cleop,
Haven't "_forgotten_" you. 💭 
I've implemented Travis-CI with Codecov including the PR comments: https://github.com/dwyl/stars/pull/3#issuecomment-272723467
the PR isn't quite done yet but you can see that it's working with the following `.travis.yml`:
https://github.com/dwyl/stars/blob/e084a225ce43f2a019720955111c41ac1d1d9bf7/.travis.yml#L8-L11

Did you have any luck? 🍀

**Comment by Cleop** [comment]
I've managed to get Travis to pass by removing the coverage script I had in my package.json before for istanbul. However I'm still getting codecov: unknown on my badge on the readme and I have no commit histories in my codecov profile.

Any ideas @nelsonic?

**Comment by nelsonic** [comment]
@Cleop good question, we could do a hangout to figure it if you have time... 🤔

**Comment by nelsonic** [comment]
@Cleop were you able to get this working?

**Comment by Gamecock** [comment]
@nelsonic I found this trying to resolve the codecov badge showing unknown in Github, when codecov.io has coverage metrics, and I noticed the dwyl/stars#3 also shows codecov status as unknown.  Does that feature no longer work?

**Comment by nelsonic** [comment]
@Gamecock Good question. 
It appears that recently Codecov have changed how they implement coverage via CI service.
I recently updated on of our JS projects https://github.com/dwyl/learn-json-web-tokens and it required me adding a `CODECOV_TOKEN` environment variable to Travis-CI to get it to work. 🙄 

The feature definitely works. We use Codecov on over 50 dwyl repositories: https://codecov.io/gh/dwyl
Ironically, the repo you have linked to (stars) is on page 3 of our list of repos: 
https://codecov.io/gh/dwyl?page=3 and shows 100% coverage:
![image](https://user-images.githubusercontent.com/194400/51540049-61954b80-1e4d-11e9-8681-eaeb0d465d75.png)
So the badge just needs to be updated ... 

```
[![codecov](https://codecov.io/gh/dwyl/stars/branch/master/graph/badge.svg)](https://codecov.io/gh/dwyl/stars)
```
[![codecov](https://codecov.io/gh/dwyl/stars/branch/master/graph/badge.svg)](https://codecov.io/gh/dwyl/stars)

```
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/stars/master.svg?style=flat-square)](http://codecov.io/github/dwyl/stars?branch=master)
```
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/stars/master.svg?style=flat-square)](http://codecov.io/github/dwyl/stars?branch=master)

**Comment by Gamecock** [comment]
Thanks, this pointed me in the correct direction.  I just had to add ?token=:graph_token to the end of my request.  
https://docs.codecov.io/reference#about-graphs
